language: java
dist: trusty

jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11

script:
  - mvn clean install jacoco:report coveralls:report
  - mvn -f examples/pom.xml clean package

addons:
   hosts:
       - travis
   hostname: travis

before_script:
  - pip install --user codecov

after_success:
  - codecov
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
  - mvn sonar:sonar -Dsonar.projectKey=javadev_underscore-java -Dsonar.organization=javadev-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=ae9ca1a96d65855cf962d904b354cc1ceb1b584d
