language: java

before_deploy:
   - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
   - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

deploy:
  provider: releases
  api_key:
    secure: Ov5ZHCh9cNZJITGkTxi+ZxM4WlXduQmoybTl70Yk0fDxOgqlnP/HEwiwBeiGuSPdY+IAUN29mtUvFsO/YIK5J6ZbJLfBGF+X14YtQK+WNtzOULNpMP/0iHeLADHd9XmyMh6KcH+CMGnX18wGAhTUy9Jt2/t7jAZFrUGdGQE/Z4SqdGM1tLlQKADzH+hfovDHE8/1P7MmfJYbPfJfGnn5MNU56OI+y8LFmpZakq3EmFH9/vOoBbgcmCe9AHq4nZD2d1VRXYkqqMB/xDfPXqi0gsywGTWvgnyznR3Emtsu6aoOARpQ4xnv05ZwcYt06UZCkuawRZEX7V8OkNSnd9eljn2R85f2NCDsUKTe3IMDtAWMIsenV9y7c3HG9Juw6ddNClQwH6XZPHWngcyAw4odEULJkvK3yhnZHIgL2563S7Pnzl/XkOjhzu31j/89ob5kKX5Fk1iwc9Yx/H4gWN/XNt59AK/lrUFKVDkJyepE2AZ7jn8IeTbH1If0ddZ0xdRAxXoe34UkbkCcSkZabL0gl7hssmTn2HqI4YAhCaWISPq0MKKFfVlfSH0VGc56nHXYuV4LfA4gM7QvMFxLRJ182fALSRtxSjvJ+jkmxQWfbBBWqvlBr/NamnZQZ5QDZsdjMiYA+yWeD4hxNgHGSgrfDDu7ZiE6QFYGPFHFDlchR3I=
  file:
    - modelmapper-module-vavr/target/modelmapper-vavr-module-$project_version.jar
  on:
    repo: julianps/modelmapper-module-vavr
    tags: true
  skip_cleanup: true
  name: $project_version

