language: java

jdk:
  - openjdk7
  - openjdk8

# whitelist
branches:
  only:
    - master
    - "2.9"

env:
  global:
    - secure: "WRMNTeyn3OIz5itsU3wzRd+QP8NNw/gvTOGqIA2wjmiNVNUVSYDL6Xk1tYYuawS2qiafaaMrEMPdFrjh1P8rsh6HRzlE7KEbHlmeYzNECvYjv7g1F42LgG5wb4kizR5BowyZbUykgys8uK7EVTrFTWXZdZOnibdhKMCyVQNfoE2imuUV3O0LnXWCNRCy2AQ4l6+ikD43uTSeunOfsJ++8sO1egiKpRE0V/P2G2Q1v7M2rNItntQkcGYAKYv+fL0WbQoW4IrpqHI+PGV95TXDIAYkC89Av6vcNJz9RLWMqp5LxWr6r7ZU/ZF/ihuAoYc78SrUB4Cp/t9nHUTwtr7bP7pmxTr/8ROxxB8obXZPRTdQhucb7l8U5sxM6Rlm+s0sT/IT56UW1kps5R6b9uyMDMAQBtCQEvhT1ab+5r/QTDa+81xbL6Kv2/dS2s6FwAg/xXlZj1/LSIUG/HlcS7/TYABvTlwSaaXYmEa6OPgEVXnZjRFY0BaTw4OmR6/KLUVkCh6fhkqE8G8MZj+ETBp2+Z8nZy4dqzHcwkr8PUyZvatcdvfwKSFdE4UFBuc22cOaO+uyupwdPbRQDhTZ2saZ6CtSZXdApwZxGIQv1rLl4iTIgrW6C2bOp5vznOkvIDQZ9SRSIJwagkgikWPMPnOjreJFFKLk5TJsifSRvsDdONM="
    - secure: "imwOCo67gO0Ul97FKngRVKMXsdpYwZPGZrQTpb8fxNw3j5KIIN0ofWnqHPsUc4wYthxB6A2JmXhTlFxvyB8ZZsWtXHeDmB6sISug6PvsxK6pLrVWnn2WybQvbv2iHRNEzNhMLp6eFygS+SNWWs81/Da7yWpCbRXd528xCDplsm26W7YAmtCRNPg7lYw6ZdKRsgJA+jEIt+byTBLAdGwcLxeLK212apCU6vgXABUapj0ifDJtUdBLcuCEk4RMrnZeqSMaFU2RoopWiyO/iHEEEXCWBHY71/FDn9wR/0lMzBpSh9zCcQnTJNcdlxu/IdJw0B/owzIaDGkX/1xx5obXkFIsqFyBK8GsEO8LOVhkOTfSgIGfaJI1l+qYHiotqvVsfGMijhKuTM1udAMfKmLepYf1M326PiVt0l8qpzIfwdFi4P44rQdEIx5paNCvOlPDaj9P0/LrP+8wDOZMUI71BHdGCNs97f+yzOFsblzsTjZS+wolGfmoYTiBo3JeY0FhNBbibVhpHG+O9AuqPjIb91Dr/LAM+WSHwVT69zNj+yE94kvfbXEQeE26VATrsLpiurJwrGr/dwaxCvMJDE5+PSKZNGbE2Rn7T/oD5cE+HuJILatkEluKhng1+qr5T/oqmZFUu2E+JOPcLylP8vUdu/cGOo1Rh8QlDX56f0/VFt0="
